### ISSUE TITLE
[Question] terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by imageje** [ppplinday/vgg16-by-ARM-Compute-Library#1]
Thanks for sharing your code.
After I downloaded your code and run, I met below messages :
    terminate called after throwing an instance of 'std::bad_alloc'
    what():  std::bad_alloc

I don't use opencl and I want to run only using neon.
Please tell me your comment.

**Comment by ppplinday** [comment]
I think there are something mistake on building library and I do not know what`s wrong with this situation. Sorry about that and I recommend you to post your issue on here:https://github.com/ARM-software/ComputeLibrary.
And finally, thanks for you to download my code and post issue!!!

**Comment by imageje** [comment]
thanks for your feedback.   I want to run your code in ARM7x 
I have two  questions..

1. Without opencl, is it possible that run your code?
2. How do you make csv files for weight and bias?

**Comment by ppplinday** [comment]
Hi!
1.It can run without opencl in CPU.
2.https://github.com/ppplinday/vgg16-by-ARM-Compute-Library/blob/12e09a77993fadacbb3be47938ad75b559ffdb13/examples/vgg16_model_arm_compute_library_NEON.cpp#L676-L691
You can see in the link. 
Any question, please feedback, thank you very much!!!

**Comment by imageje** [comment]
Thank for your feedback!
I found our memory is too lack. Your comment is 1.5GB at least. But our system has 300MB. 
I will tried another network from now.

If I have caffe model or tensorflow model, how do I make csv files? do you have converter?
Have you ever tried another network using Arm complute library?

Thanks very much.

**Comment by ppplinday** [comment]
I also run vgg16 in caffe and tensorflow. However, I can not find the way to make csv file. I downloaded vgg16 csv file in the Internet. 

And I tried to run another network using Arm compute library, such as Alexnet and  Alexnet without fullconnection layer 6 7. You can find the code in my github.

Have a good day!!!!

**Comment by imageje** [comment]
Thanks for your feedback~
